// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.Retail.V2Alpha.Outputs
{

    [OutputType]
    public sealed class GoogleCloudRetailV2alphaIntervalResponse
    {
        /// <summary>
        /// Exclusive upper bound.
        /// </summary>
        public readonly double ExclusiveMaximum;
        /// <summary>
        /// Exclusive lower bound.
        /// </summary>
        public readonly double ExclusiveMinimum;
        /// <summary>
        /// Inclusive upper bound.
        /// </summary>
        public readonly double Maximum;
        /// <summary>
        /// Inclusive lower bound.
        /// </summary>
        public readonly double Minimum;

        [OutputConstructor]
        private GoogleCloudRetailV2alphaIntervalResponse(
            double exclusiveMaximum,

            double exclusiveMinimum,

            double maximum,

            double minimum)
        {
            ExclusiveMaximum = exclusiveMaximum;
            ExclusiveMinimum = exclusiveMinimum;
            Maximum = maximum;
            Minimum = minimum;
        }
    }
}
