// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleCloud.Dns.V1.Outputs
{

    [OutputType]
    public sealed class PolicyAlternativeNameServerConfigResponse
    {
        public readonly string Kind;
        /// <summary>
        /// Sets an alternative name server for the associated networks. When specified, all DNS queries are forwarded to a name server that you choose. Names such as .internal are not available when an alternative name server is specified.
        /// </summary>
        public readonly ImmutableArray<Outputs.PolicyAlternativeNameServerConfigTargetNameServerResponse> TargetNameServers;

        [OutputConstructor]
        private PolicyAlternativeNameServerConfigResponse(
            string kind,

            ImmutableArray<Outputs.PolicyAlternativeNameServerConfigTargetNameServerResponse> targetNameServers)
        {
            Kind = kind;
            TargetNameServers = targetNameServers;
        }
    }
}
