// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates a notification config.
// Auto-naming is currently not supported for this resource.
type FolderNotificationConfig struct {
	pulumi.CustomResourceState

	// Required. Unique identifier provided by the client within the parent scope. It must be between 1 and 128 characters, and contains alphanumeric characters, underscores or hyphens only.
	ConfigId pulumi.StringOutput `pulumi:"configId"`
	// The description of the notification config (max of 1024 characters).
	Description pulumi.StringOutput `pulumi:"description"`
	FolderId    pulumi.StringOutput `pulumi:"folderId"`
	// The relative resource name of this notification config. See: https://cloud.google.com/apis/design/resource_names#relative_resource_name Example: "organizations/{organization_id}/notificationConfigs/notify_public_bucket", "folders/{folder_id}/notificationConfigs/notify_public_bucket", or "projects/{project_id}/notificationConfigs/notify_public_bucket".
	Name pulumi.StringOutput `pulumi:"name"`
	// The Pub/Sub topic to send notifications to. Its format is "projects/[project_id]/topics/[topic]".
	PubsubTopic pulumi.StringOutput `pulumi:"pubsubTopic"`
	// The service account that needs "pubsub.topics.publish" permission to publish to the Pub/Sub topic.
	ServiceAccount pulumi.StringOutput `pulumi:"serviceAccount"`
	// The config for triggering streaming-based notifications.
	StreamingConfig StreamingConfigResponseOutput `pulumi:"streamingConfig"`
}

// NewFolderNotificationConfig registers a new resource with the given unique name, arguments, and options.
func NewFolderNotificationConfig(ctx *pulumi.Context,
	name string, args *FolderNotificationConfigArgs, opts ...pulumi.ResourceOption) (*FolderNotificationConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConfigId == nil {
		return nil, errors.New("invalid value for required argument 'ConfigId'")
	}
	if args.FolderId == nil {
		return nil, errors.New("invalid value for required argument 'FolderId'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"configId",
		"folderId",
	})
	opts = append(opts, replaceOnChanges)
	var resource FolderNotificationConfig
	err := ctx.RegisterResource("google-native:securitycenter/v1:FolderNotificationConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFolderNotificationConfig gets an existing FolderNotificationConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFolderNotificationConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FolderNotificationConfigState, opts ...pulumi.ResourceOption) (*FolderNotificationConfig, error) {
	var resource FolderNotificationConfig
	err := ctx.ReadResource("google-native:securitycenter/v1:FolderNotificationConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FolderNotificationConfig resources.
type folderNotificationConfigState struct {
}

type FolderNotificationConfigState struct {
}

func (FolderNotificationConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*folderNotificationConfigState)(nil)).Elem()
}

type folderNotificationConfigArgs struct {
	// Required. Unique identifier provided by the client within the parent scope. It must be between 1 and 128 characters, and contains alphanumeric characters, underscores or hyphens only.
	ConfigId string `pulumi:"configId"`
	// The description of the notification config (max of 1024 characters).
	Description *string `pulumi:"description"`
	FolderId    string  `pulumi:"folderId"`
	// The relative resource name of this notification config. See: https://cloud.google.com/apis/design/resource_names#relative_resource_name Example: "organizations/{organization_id}/notificationConfigs/notify_public_bucket", "folders/{folder_id}/notificationConfigs/notify_public_bucket", or "projects/{project_id}/notificationConfigs/notify_public_bucket".
	Name *string `pulumi:"name"`
	// The Pub/Sub topic to send notifications to. Its format is "projects/[project_id]/topics/[topic]".
	PubsubTopic *string `pulumi:"pubsubTopic"`
	// The config for triggering streaming-based notifications.
	StreamingConfig *StreamingConfig `pulumi:"streamingConfig"`
}

// The set of arguments for constructing a FolderNotificationConfig resource.
type FolderNotificationConfigArgs struct {
	// Required. Unique identifier provided by the client within the parent scope. It must be between 1 and 128 characters, and contains alphanumeric characters, underscores or hyphens only.
	ConfigId pulumi.StringInput
	// The description of the notification config (max of 1024 characters).
	Description pulumi.StringPtrInput
	FolderId    pulumi.StringInput
	// The relative resource name of this notification config. See: https://cloud.google.com/apis/design/resource_names#relative_resource_name Example: "organizations/{organization_id}/notificationConfigs/notify_public_bucket", "folders/{folder_id}/notificationConfigs/notify_public_bucket", or "projects/{project_id}/notificationConfigs/notify_public_bucket".
	Name pulumi.StringPtrInput
	// The Pub/Sub topic to send notifications to. Its format is "projects/[project_id]/topics/[topic]".
	PubsubTopic pulumi.StringPtrInput
	// The config for triggering streaming-based notifications.
	StreamingConfig StreamingConfigPtrInput
}

func (FolderNotificationConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*folderNotificationConfigArgs)(nil)).Elem()
}

type FolderNotificationConfigInput interface {
	pulumi.Input

	ToFolderNotificationConfigOutput() FolderNotificationConfigOutput
	ToFolderNotificationConfigOutputWithContext(ctx context.Context) FolderNotificationConfigOutput
}

func (*FolderNotificationConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**FolderNotificationConfig)(nil)).Elem()
}

func (i *FolderNotificationConfig) ToFolderNotificationConfigOutput() FolderNotificationConfigOutput {
	return i.ToFolderNotificationConfigOutputWithContext(context.Background())
}

func (i *FolderNotificationConfig) ToFolderNotificationConfigOutputWithContext(ctx context.Context) FolderNotificationConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FolderNotificationConfigOutput)
}

type FolderNotificationConfigOutput struct{ *pulumi.OutputState }

func (FolderNotificationConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FolderNotificationConfig)(nil)).Elem()
}

func (o FolderNotificationConfigOutput) ToFolderNotificationConfigOutput() FolderNotificationConfigOutput {
	return o
}

func (o FolderNotificationConfigOutput) ToFolderNotificationConfigOutputWithContext(ctx context.Context) FolderNotificationConfigOutput {
	return o
}

// Required. Unique identifier provided by the client within the parent scope. It must be between 1 and 128 characters, and contains alphanumeric characters, underscores or hyphens only.
func (o FolderNotificationConfigOutput) ConfigId() pulumi.StringOutput {
	return o.ApplyT(func(v *FolderNotificationConfig) pulumi.StringOutput { return v.ConfigId }).(pulumi.StringOutput)
}

// The description of the notification config (max of 1024 characters).
func (o FolderNotificationConfigOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *FolderNotificationConfig) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o FolderNotificationConfigOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v *FolderNotificationConfig) pulumi.StringOutput { return v.FolderId }).(pulumi.StringOutput)
}

// The relative resource name of this notification config. See: https://cloud.google.com/apis/design/resource_names#relative_resource_name Example: "organizations/{organization_id}/notificationConfigs/notify_public_bucket", "folders/{folder_id}/notificationConfigs/notify_public_bucket", or "projects/{project_id}/notificationConfigs/notify_public_bucket".
func (o FolderNotificationConfigOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *FolderNotificationConfig) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The Pub/Sub topic to send notifications to. Its format is "projects/[project_id]/topics/[topic]".
func (o FolderNotificationConfigOutput) PubsubTopic() pulumi.StringOutput {
	return o.ApplyT(func(v *FolderNotificationConfig) pulumi.StringOutput { return v.PubsubTopic }).(pulumi.StringOutput)
}

// The service account that needs "pubsub.topics.publish" permission to publish to the Pub/Sub topic.
func (o FolderNotificationConfigOutput) ServiceAccount() pulumi.StringOutput {
	return o.ApplyT(func(v *FolderNotificationConfig) pulumi.StringOutput { return v.ServiceAccount }).(pulumi.StringOutput)
}

// The config for triggering streaming-based notifications.
func (o FolderNotificationConfigOutput) StreamingConfig() StreamingConfigResponseOutput {
	return o.ApplyT(func(v *FolderNotificationConfig) StreamingConfigResponseOutput { return v.StreamingConfig }).(StreamingConfigResponseOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FolderNotificationConfigInput)(nil)).Elem(), &FolderNotificationConfig{})
	pulumi.RegisterOutputType(FolderNotificationConfigOutput{})
}
