// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.googlenative.compute.alpha.enums;

import com.pulumi.core.annotations.EnumType;
import java.lang.String;
import java.util.Objects;
import java.util.StringJoiner;

    @EnumType
    public enum NetworkInterfaceSubInterfaceIpAllocationMode {
        /**
         * Allocates an internal IPv4 IP address from subnets secondary IP Range.
         * 
         */
        AllocateIp("ALLOCATE_IP"),
        /**
         * No IP allocation is done for the subinterface.
         * 
         */
        DoNotAllocateIp("DO_NOT_ALLOCATE_IP"),
        Unspecified("UNSPECIFIED");

        private final String value;

        NetworkInterfaceSubInterfaceIpAllocationMode(String value) {
            this.value = Objects.requireNonNull(value);
        }

        @EnumType.Converter
        public String getValue() {
            return this.value;
        }

        @Override
        public String toString() {
            return new StringJoiner(", ", "NetworkInterfaceSubInterfaceIpAllocationMode[", "]")
                .add("value='" + this.value + "'")
                .toString();
        }
    }
