// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.googlenative.cloudiot.v1.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * The configuration for forwarding telemetry events.
 * 
 */
public final class EventNotificationConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final EventNotificationConfigArgs Empty = new EventNotificationConfigArgs();

    /**
     * A Cloud Pub/Sub topic name. For example, `projects/myProject/topics/deviceEvents`.
     * 
     */
    @Import(name="pubsubTopicName")
    private @Nullable Output<String> pubsubTopicName;

    /**
     * @return A Cloud Pub/Sub topic name. For example, `projects/myProject/topics/deviceEvents`.
     * 
     */
    public Optional<Output<String>> pubsubTopicName() {
        return Optional.ofNullable(this.pubsubTopicName);
    }

    /**
     * If the subfolder name matches this string exactly, this configuration will be used. The string must not include the leading &#39;/&#39; character. If empty, all strings are matched. This field is used only for telemetry events; subfolders are not supported for state changes.
     * 
     */
    @Import(name="subfolderMatches")
    private @Nullable Output<String> subfolderMatches;

    /**
     * @return If the subfolder name matches this string exactly, this configuration will be used. The string must not include the leading &#39;/&#39; character. If empty, all strings are matched. This field is used only for telemetry events; subfolders are not supported for state changes.
     * 
     */
    public Optional<Output<String>> subfolderMatches() {
        return Optional.ofNullable(this.subfolderMatches);
    }

    private EventNotificationConfigArgs() {}

    private EventNotificationConfigArgs(EventNotificationConfigArgs $) {
        this.pubsubTopicName = $.pubsubTopicName;
        this.subfolderMatches = $.subfolderMatches;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EventNotificationConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EventNotificationConfigArgs $;

        public Builder() {
            $ = new EventNotificationConfigArgs();
        }

        public Builder(EventNotificationConfigArgs defaults) {
            $ = new EventNotificationConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param pubsubTopicName A Cloud Pub/Sub topic name. For example, `projects/myProject/topics/deviceEvents`.
         * 
         * @return builder
         * 
         */
        public Builder pubsubTopicName(@Nullable Output<String> pubsubTopicName) {
            $.pubsubTopicName = pubsubTopicName;
            return this;
        }

        /**
         * @param pubsubTopicName A Cloud Pub/Sub topic name. For example, `projects/myProject/topics/deviceEvents`.
         * 
         * @return builder
         * 
         */
        public Builder pubsubTopicName(String pubsubTopicName) {
            return pubsubTopicName(Output.of(pubsubTopicName));
        }

        /**
         * @param subfolderMatches If the subfolder name matches this string exactly, this configuration will be used. The string must not include the leading &#39;/&#39; character. If empty, all strings are matched. This field is used only for telemetry events; subfolders are not supported for state changes.
         * 
         * @return builder
         * 
         */
        public Builder subfolderMatches(@Nullable Output<String> subfolderMatches) {
            $.subfolderMatches = subfolderMatches;
            return this;
        }

        /**
         * @param subfolderMatches If the subfolder name matches this string exactly, this configuration will be used. The string must not include the leading &#39;/&#39; character. If empty, all strings are matched. This field is used only for telemetry events; subfolders are not supported for state changes.
         * 
         * @return builder
         * 
         */
        public Builder subfolderMatches(String subfolderMatches) {
            return subfolderMatches(Output.of(subfolderMatches));
        }

        public EventNotificationConfigArgs build() {
            return $;
        }
    }

}
