// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.DeploymentManager.V2Beta.Outputs
{

    [OutputType]
    public sealed class SetCommonInstanceMetadataOperationMetadataResponse
    {
        /// <summary>
        /// The client operation id.
        /// </summary>
        public readonly string ClientOperationId;
        /// <summary>
        /// Status information per location (location name is key). Example key: zones/us-central1-a
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.SetCommonInstanceMetadataOperationMetadataPerLocationOperationInfoResponse> PerLocationOperations;

        [OutputConstructor]
        private SetCommonInstanceMetadataOperationMetadataResponse(
            string clientOperationId,

            ImmutableDictionary<string, Outputs.SetCommonInstanceMetadataOperationMetadataPerLocationOperationInfoResponse> perLocationOperations)
        {
            ClientOperationId = clientOperationId;
            PerLocationOperations = perLocationOperations;
        }
    }
}
