// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.IdentityToolkit.V2.Outputs
{

    /// <summary>
    /// Configuration for logging requests made to this project to Stackdriver Logging
    /// </summary>
    [OutputType]
    public sealed class GoogleCloudIdentitytoolkitAdminV2RequestLoggingResponse
    {
        /// <summary>
        /// Whether logging is enabled for this project or not.
        /// </summary>
        public readonly bool Enabled;

        [OutputConstructor]
        private GoogleCloudIdentitytoolkitAdminV2RequestLoggingResponse(bool enabled)
        {
            Enabled = enabled;
        }
    }
}
