// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.Run.V2.Outputs
{

    /// <summary>
    /// Scaling settings applied at the service level rather than at the revision level.
    /// </summary>
    [OutputType]
    public sealed class GoogleCloudRunV2ServiceScalingResponse
    {
        /// <summary>
        /// total min instances for the service. This number of instances is divided among all revisions with specified traffic based on the percent of traffic they are receiving. (ALPHA)
        /// </summary>
        public readonly int MinInstanceCount;

        [OutputConstructor]
        private GoogleCloudRunV2ServiceScalingResponse(int minInstanceCount)
        {
            MinInstanceCount = minInstanceCount;
        }
    }
}
