# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs

__all__ = [
    'GetModelResult',
    'AwaitableGetModelResult',
    'get_model',
    'get_model_output',
]

@pulumi.output_type
class GetModelResult:
    def __init__(__self__, artifact_uri=None, base_model_source=None, container_spec=None, create_time=None, data_stats=None, deployed_models=None, description=None, display_name=None, encryption_spec=None, etag=None, explanation_spec=None, labels=None, metadata=None, metadata_artifact=None, metadata_schema_uri=None, model_source_info=None, name=None, original_model_info=None, pipeline_job=None, predict_schemata=None, supported_deployment_resources_types=None, supported_export_formats=None, supported_input_storage_formats=None, supported_output_storage_formats=None, training_pipeline=None, update_time=None, version_aliases=None, version_create_time=None, version_description=None, version_id=None, version_update_time=None):
        if artifact_uri and not isinstance(artifact_uri, str):
            raise TypeError("Expected argument 'artifact_uri' to be a str")
        pulumi.set(__self__, "artifact_uri", artifact_uri)
        if base_model_source and not isinstance(base_model_source, dict):
            raise TypeError("Expected argument 'base_model_source' to be a dict")
        pulumi.set(__self__, "base_model_source", base_model_source)
        if container_spec and not isinstance(container_spec, dict):
            raise TypeError("Expected argument 'container_spec' to be a dict")
        pulumi.set(__self__, "container_spec", container_spec)
        if create_time and not isinstance(create_time, str):
            raise TypeError("Expected argument 'create_time' to be a str")
        pulumi.set(__self__, "create_time", create_time)
        if data_stats and not isinstance(data_stats, dict):
            raise TypeError("Expected argument 'data_stats' to be a dict")
        pulumi.set(__self__, "data_stats", data_stats)
        if deployed_models and not isinstance(deployed_models, list):
            raise TypeError("Expected argument 'deployed_models' to be a list")
        pulumi.set(__self__, "deployed_models", deployed_models)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if display_name and not isinstance(display_name, str):
            raise TypeError("Expected argument 'display_name' to be a str")
        pulumi.set(__self__, "display_name", display_name)
        if encryption_spec and not isinstance(encryption_spec, dict):
            raise TypeError("Expected argument 'encryption_spec' to be a dict")
        pulumi.set(__self__, "encryption_spec", encryption_spec)
        if etag and not isinstance(etag, str):
            raise TypeError("Expected argument 'etag' to be a str")
        pulumi.set(__self__, "etag", etag)
        if explanation_spec and not isinstance(explanation_spec, dict):
            raise TypeError("Expected argument 'explanation_spec' to be a dict")
        pulumi.set(__self__, "explanation_spec", explanation_spec)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if metadata and not isinstance(metadata, dict):
            raise TypeError("Expected argument 'metadata' to be a dict")
        pulumi.set(__self__, "metadata", metadata)
        if metadata_artifact and not isinstance(metadata_artifact, str):
            raise TypeError("Expected argument 'metadata_artifact' to be a str")
        pulumi.set(__self__, "metadata_artifact", metadata_artifact)
        if metadata_schema_uri and not isinstance(metadata_schema_uri, str):
            raise TypeError("Expected argument 'metadata_schema_uri' to be a str")
        pulumi.set(__self__, "metadata_schema_uri", metadata_schema_uri)
        if model_source_info and not isinstance(model_source_info, dict):
            raise TypeError("Expected argument 'model_source_info' to be a dict")
        pulumi.set(__self__, "model_source_info", model_source_info)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if original_model_info and not isinstance(original_model_info, dict):
            raise TypeError("Expected argument 'original_model_info' to be a dict")
        pulumi.set(__self__, "original_model_info", original_model_info)
        if pipeline_job and not isinstance(pipeline_job, str):
            raise TypeError("Expected argument 'pipeline_job' to be a str")
        pulumi.set(__self__, "pipeline_job", pipeline_job)
        if predict_schemata and not isinstance(predict_schemata, dict):
            raise TypeError("Expected argument 'predict_schemata' to be a dict")
        pulumi.set(__self__, "predict_schemata", predict_schemata)
        if supported_deployment_resources_types and not isinstance(supported_deployment_resources_types, list):
            raise TypeError("Expected argument 'supported_deployment_resources_types' to be a list")
        pulumi.set(__self__, "supported_deployment_resources_types", supported_deployment_resources_types)
        if supported_export_formats and not isinstance(supported_export_formats, list):
            raise TypeError("Expected argument 'supported_export_formats' to be a list")
        pulumi.set(__self__, "supported_export_formats", supported_export_formats)
        if supported_input_storage_formats and not isinstance(supported_input_storage_formats, list):
            raise TypeError("Expected argument 'supported_input_storage_formats' to be a list")
        pulumi.set(__self__, "supported_input_storage_formats", supported_input_storage_formats)
        if supported_output_storage_formats and not isinstance(supported_output_storage_formats, list):
            raise TypeError("Expected argument 'supported_output_storage_formats' to be a list")
        pulumi.set(__self__, "supported_output_storage_formats", supported_output_storage_formats)
        if training_pipeline and not isinstance(training_pipeline, str):
            raise TypeError("Expected argument 'training_pipeline' to be a str")
        pulumi.set(__self__, "training_pipeline", training_pipeline)
        if update_time and not isinstance(update_time, str):
            raise TypeError("Expected argument 'update_time' to be a str")
        pulumi.set(__self__, "update_time", update_time)
        if version_aliases and not isinstance(version_aliases, list):
            raise TypeError("Expected argument 'version_aliases' to be a list")
        pulumi.set(__self__, "version_aliases", version_aliases)
        if version_create_time and not isinstance(version_create_time, str):
            raise TypeError("Expected argument 'version_create_time' to be a str")
        pulumi.set(__self__, "version_create_time", version_create_time)
        if version_description and not isinstance(version_description, str):
            raise TypeError("Expected argument 'version_description' to be a str")
        pulumi.set(__self__, "version_description", version_description)
        if version_id and not isinstance(version_id, str):
            raise TypeError("Expected argument 'version_id' to be a str")
        pulumi.set(__self__, "version_id", version_id)
        if version_update_time and not isinstance(version_update_time, str):
            raise TypeError("Expected argument 'version_update_time' to be a str")
        pulumi.set(__self__, "version_update_time", version_update_time)

    @property
    @pulumi.getter(name="artifactUri")
    def artifact_uri(self) -> str:
        """
        Immutable. The path to the directory containing the Model artifact and any of its supporting files. Not required for AutoML Models.
        """
        return pulumi.get(self, "artifact_uri")

    @property
    @pulumi.getter(name="baseModelSource")
    def base_model_source(self) -> 'outputs.GoogleCloudAiplatformV1ModelBaseModelSourceResponse':
        """
        Optional. User input field to specify the base model source. Currently it only supports specifing the Model Garden models and Genie models.
        """
        return pulumi.get(self, "base_model_source")

    @property
    @pulumi.getter(name="containerSpec")
    def container_spec(self) -> 'outputs.GoogleCloudAiplatformV1ModelContainerSpecResponse':
        """
        Input only. The specification of the container that is to be used when deploying this Model. The specification is ingested upon ModelService.UploadModel, and all binaries it contains are copied and stored internally by Vertex AI. Not required for AutoML Models.
        """
        return pulumi.get(self, "container_spec")

    @property
    @pulumi.getter(name="createTime")
    def create_time(self) -> str:
        """
        Timestamp when this Model was uploaded into Vertex AI.
        """
        return pulumi.get(self, "create_time")

    @property
    @pulumi.getter(name="dataStats")
    def data_stats(self) -> 'outputs.GoogleCloudAiplatformV1ModelDataStatsResponse':
        """
        Stats of data used for training or evaluating the Model. Only populated when the Model is trained by a TrainingPipeline with data_input_config.
        """
        return pulumi.get(self, "data_stats")

    @property
    @pulumi.getter(name="deployedModels")
    def deployed_models(self) -> Sequence['outputs.GoogleCloudAiplatformV1DeployedModelRefResponse']:
        """
        The pointers to DeployedModels created from this Model. Note that Model could have been deployed to Endpoints in different Locations.
        """
        return pulumi.get(self, "deployed_models")

    @property
    @pulumi.getter
    def description(self) -> str:
        """
        The description of the Model.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter(name="displayName")
    def display_name(self) -> str:
        """
        The display name of the Model. The name can be up to 128 characters long and can consist of any UTF-8 characters.
        """
        return pulumi.get(self, "display_name")

    @property
    @pulumi.getter(name="encryptionSpec")
    def encryption_spec(self) -> 'outputs.GoogleCloudAiplatformV1EncryptionSpecResponse':
        """
        Customer-managed encryption key spec for a Model. If set, this Model and all sub-resources of this Model will be secured by this key.
        """
        return pulumi.get(self, "encryption_spec")

    @property
    @pulumi.getter
    def etag(self) -> str:
        """
        Used to perform consistent read-modify-write updates. If not set, a blind "overwrite" update happens.
        """
        return pulumi.get(self, "etag")

    @property
    @pulumi.getter(name="explanationSpec")
    def explanation_spec(self) -> 'outputs.GoogleCloudAiplatformV1ExplanationSpecResponse':
        """
        The default explanation specification for this Model. The Model can be used for requesting explanation after being deployed if it is populated. The Model can be used for batch explanation if it is populated. All fields of the explanation_spec can be overridden by explanation_spec of DeployModelRequest.deployed_model, or explanation_spec of BatchPredictionJob. If the default explanation specification is not set for this Model, this Model can still be used for requesting explanation by setting explanation_spec of DeployModelRequest.deployed_model and for batch explanation by setting explanation_spec of BatchPredictionJob.
        """
        return pulumi.get(self, "explanation_spec")

    @property
    @pulumi.getter
    def labels(self) -> Mapping[str, str]:
        """
        The labels with user-defined metadata to organize your Models. Label keys and values can be no longer than 64 characters (Unicode codepoints), can only contain lowercase letters, numeric characters, underscores and dashes. International characters are allowed. See https://goo.gl/xmQnxf for more information and examples of labels.
        """
        return pulumi.get(self, "labels")

    @property
    @pulumi.getter
    def metadata(self) -> Any:
        """
        Immutable. An additional information about the Model; the schema of the metadata can be found in metadata_schema. Unset if the Model does not have any additional information.
        """
        return pulumi.get(self, "metadata")

    @property
    @pulumi.getter(name="metadataArtifact")
    def metadata_artifact(self) -> str:
        """
        The resource name of the Artifact that was created in MetadataStore when creating the Model. The Artifact resource name pattern is `projects/{project}/locations/{location}/metadataStores/{metadata_store}/artifacts/{artifact}`.
        """
        return pulumi.get(self, "metadata_artifact")

    @property
    @pulumi.getter(name="metadataSchemaUri")
    def metadata_schema_uri(self) -> str:
        """
        Immutable. Points to a YAML file stored on Google Cloud Storage describing additional information about the Model, that is specific to it. Unset if the Model does not have any additional information. The schema is defined as an OpenAPI 3.0.2 [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#schemaObject). AutoML Models always have this field populated by Vertex AI, if no additional metadata is needed, this field is set to an empty string. Note: The URI given on output will be immutable and probably different, including the URI scheme, than the one given on input. The output URI will point to a location where the user only has a read access.
        """
        return pulumi.get(self, "metadata_schema_uri")

    @property
    @pulumi.getter(name="modelSourceInfo")
    def model_source_info(self) -> 'outputs.GoogleCloudAiplatformV1ModelSourceInfoResponse':
        """
        Source of a model. It can either be automl training pipeline, custom training pipeline, BigQuery ML, or saved and tuned from Genie or Model Garden.
        """
        return pulumi.get(self, "model_source_info")

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        The resource name of the Model.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="originalModelInfo")
    def original_model_info(self) -> 'outputs.GoogleCloudAiplatformV1ModelOriginalModelInfoResponse':
        """
        If this Model is a copy of another Model, this contains info about the original.
        """
        return pulumi.get(self, "original_model_info")

    @property
    @pulumi.getter(name="pipelineJob")
    def pipeline_job(self) -> str:
        """
        Optional. This field is populated if the model is produced by a pipeline job.
        """
        return pulumi.get(self, "pipeline_job")

    @property
    @pulumi.getter(name="predictSchemata")
    def predict_schemata(self) -> 'outputs.GoogleCloudAiplatformV1PredictSchemataResponse':
        """
        The schemata that describe formats of the Model's predictions and explanations as given and returned via PredictionService.Predict and PredictionService.Explain.
        """
        return pulumi.get(self, "predict_schemata")

    @property
    @pulumi.getter(name="supportedDeploymentResourcesTypes")
    def supported_deployment_resources_types(self) -> Sequence[str]:
        """
        When this Model is deployed, its prediction resources are described by the `prediction_resources` field of the Endpoint.deployed_models object. Because not all Models support all resource configuration types, the configuration types this Model supports are listed here. If no configuration types are listed, the Model cannot be deployed to an Endpoint and does not support online predictions (PredictionService.Predict or PredictionService.Explain). Such a Model can serve predictions by using a BatchPredictionJob, if it has at least one entry each in supported_input_storage_formats and supported_output_storage_formats.
        """
        return pulumi.get(self, "supported_deployment_resources_types")

    @property
    @pulumi.getter(name="supportedExportFormats")
    def supported_export_formats(self) -> Sequence['outputs.GoogleCloudAiplatformV1ModelExportFormatResponse']:
        """
        The formats in which this Model may be exported. If empty, this Model is not available for export.
        """
        return pulumi.get(self, "supported_export_formats")

    @property
    @pulumi.getter(name="supportedInputStorageFormats")
    def supported_input_storage_formats(self) -> Sequence[str]:
        """
        The formats this Model supports in BatchPredictionJob.input_config. If PredictSchemata.instance_schema_uri exists, the instances should be given as per that schema. The possible formats are: * `jsonl` The JSON Lines format, where each instance is a single line. Uses GcsSource. * `csv` The CSV format, where each instance is a single comma-separated line. The first line in the file is the header, containing comma-separated field names. Uses GcsSource. * `tf-record` The TFRecord format, where each instance is a single record in tfrecord syntax. Uses GcsSource. * `tf-record-gzip` Similar to `tf-record`, but the file is gzipped. Uses GcsSource. * `bigquery` Each instance is a single row in BigQuery. Uses BigQuerySource. * `file-list` Each line of the file is the location of an instance to process, uses `gcs_source` field of the InputConfig object. If this Model doesn't support any of these formats it means it cannot be used with a BatchPredictionJob. However, if it has supported_deployment_resources_types, it could serve online predictions by using PredictionService.Predict or PredictionService.Explain.
        """
        return pulumi.get(self, "supported_input_storage_formats")

    @property
    @pulumi.getter(name="supportedOutputStorageFormats")
    def supported_output_storage_formats(self) -> Sequence[str]:
        """
        The formats this Model supports in BatchPredictionJob.output_config. If both PredictSchemata.instance_schema_uri and PredictSchemata.prediction_schema_uri exist, the predictions are returned together with their instances. In other words, the prediction has the original instance data first, followed by the actual prediction content (as per the schema). The possible formats are: * `jsonl` The JSON Lines format, where each prediction is a single line. Uses GcsDestination. * `csv` The CSV format, where each prediction is a single comma-separated line. The first line in the file is the header, containing comma-separated field names. Uses GcsDestination. * `bigquery` Each prediction is a single row in a BigQuery table, uses BigQueryDestination . If this Model doesn't support any of these formats it means it cannot be used with a BatchPredictionJob. However, if it has supported_deployment_resources_types, it could serve online predictions by using PredictionService.Predict or PredictionService.Explain.
        """
        return pulumi.get(self, "supported_output_storage_formats")

    @property
    @pulumi.getter(name="trainingPipeline")
    def training_pipeline(self) -> str:
        """
        The resource name of the TrainingPipeline that uploaded this Model, if any.
        """
        return pulumi.get(self, "training_pipeline")

    @property
    @pulumi.getter(name="updateTime")
    def update_time(self) -> str:
        """
        Timestamp when this Model was most recently updated.
        """
        return pulumi.get(self, "update_time")

    @property
    @pulumi.getter(name="versionAliases")
    def version_aliases(self) -> Sequence[str]:
        """
        User provided version aliases so that a model version can be referenced via alias (i.e. `projects/{project}/locations/{location}/models/{model_id}@{version_alias}` instead of auto-generated version id (i.e. `projects/{project}/locations/{location}/models/{model_id}@{version_id})`. The format is a-z{0,126}[a-z0-9] to distinguish from version_id. A default version alias will be created for the first version of the model, and there must be exactly one default version alias for a model.
        """
        return pulumi.get(self, "version_aliases")

    @property
    @pulumi.getter(name="versionCreateTime")
    def version_create_time(self) -> str:
        """
        Timestamp when this version was created.
        """
        return pulumi.get(self, "version_create_time")

    @property
    @pulumi.getter(name="versionDescription")
    def version_description(self) -> str:
        """
        The description of this version.
        """
        return pulumi.get(self, "version_description")

    @property
    @pulumi.getter(name="versionId")
    def version_id(self) -> str:
        """
        Immutable. The version ID of the model. A new version is committed when a new model version is uploaded or trained under an existing model id. It is an auto-incrementing decimal number in string representation.
        """
        return pulumi.get(self, "version_id")

    @property
    @pulumi.getter(name="versionUpdateTime")
    def version_update_time(self) -> str:
        """
        Timestamp when this version was most recently updated.
        """
        return pulumi.get(self, "version_update_time")


class AwaitableGetModelResult(GetModelResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetModelResult(
            artifact_uri=self.artifact_uri,
            base_model_source=self.base_model_source,
            container_spec=self.container_spec,
            create_time=self.create_time,
            data_stats=self.data_stats,
            deployed_models=self.deployed_models,
            description=self.description,
            display_name=self.display_name,
            encryption_spec=self.encryption_spec,
            etag=self.etag,
            explanation_spec=self.explanation_spec,
            labels=self.labels,
            metadata=self.metadata,
            metadata_artifact=self.metadata_artifact,
            metadata_schema_uri=self.metadata_schema_uri,
            model_source_info=self.model_source_info,
            name=self.name,
            original_model_info=self.original_model_info,
            pipeline_job=self.pipeline_job,
            predict_schemata=self.predict_schemata,
            supported_deployment_resources_types=self.supported_deployment_resources_types,
            supported_export_formats=self.supported_export_formats,
            supported_input_storage_formats=self.supported_input_storage_formats,
            supported_output_storage_formats=self.supported_output_storage_formats,
            training_pipeline=self.training_pipeline,
            update_time=self.update_time,
            version_aliases=self.version_aliases,
            version_create_time=self.version_create_time,
            version_description=self.version_description,
            version_id=self.version_id,
            version_update_time=self.version_update_time)


def get_model(location: Optional[str] = None,
              model_id: Optional[str] = None,
              project: Optional[str] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetModelResult:
    """
    Gets a Model.
    """
    __args__ = dict()
    __args__['location'] = location
    __args__['modelId'] = model_id
    __args__['project'] = project
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('google-native:aiplatform/v1:getModel', __args__, opts=opts, typ=GetModelResult).value

    return AwaitableGetModelResult(
        artifact_uri=pulumi.get(__ret__, 'artifact_uri'),
        base_model_source=pulumi.get(__ret__, 'base_model_source'),
        container_spec=pulumi.get(__ret__, 'container_spec'),
        create_time=pulumi.get(__ret__, 'create_time'),
        data_stats=pulumi.get(__ret__, 'data_stats'),
        deployed_models=pulumi.get(__ret__, 'deployed_models'),
        description=pulumi.get(__ret__, 'description'),
        display_name=pulumi.get(__ret__, 'display_name'),
        encryption_spec=pulumi.get(__ret__, 'encryption_spec'),
        etag=pulumi.get(__ret__, 'etag'),
        explanation_spec=pulumi.get(__ret__, 'explanation_spec'),
        labels=pulumi.get(__ret__, 'labels'),
        metadata=pulumi.get(__ret__, 'metadata'),
        metadata_artifact=pulumi.get(__ret__, 'metadata_artifact'),
        metadata_schema_uri=pulumi.get(__ret__, 'metadata_schema_uri'),
        model_source_info=pulumi.get(__ret__, 'model_source_info'),
        name=pulumi.get(__ret__, 'name'),
        original_model_info=pulumi.get(__ret__, 'original_model_info'),
        pipeline_job=pulumi.get(__ret__, 'pipeline_job'),
        predict_schemata=pulumi.get(__ret__, 'predict_schemata'),
        supported_deployment_resources_types=pulumi.get(__ret__, 'supported_deployment_resources_types'),
        supported_export_formats=pulumi.get(__ret__, 'supported_export_formats'),
        supported_input_storage_formats=pulumi.get(__ret__, 'supported_input_storage_formats'),
        supported_output_storage_formats=pulumi.get(__ret__, 'supported_output_storage_formats'),
        training_pipeline=pulumi.get(__ret__, 'training_pipeline'),
        update_time=pulumi.get(__ret__, 'update_time'),
        version_aliases=pulumi.get(__ret__, 'version_aliases'),
        version_create_time=pulumi.get(__ret__, 'version_create_time'),
        version_description=pulumi.get(__ret__, 'version_description'),
        version_id=pulumi.get(__ret__, 'version_id'),
        version_update_time=pulumi.get(__ret__, 'version_update_time'))


@_utilities.lift_output_func(get_model)
def get_model_output(location: Optional[pulumi.Input[str]] = None,
                     model_id: Optional[pulumi.Input[str]] = None,
                     project: Optional[pulumi.Input[Optional[str]]] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetModelResult]:
    """
    Gets a Model.
    """
    ...
