// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

/**
 * Creates a job trigger to run DLP actions such as scanning storage for sensitive information on a set schedule. See https://cloud.google.com/dlp/docs/creating-job-triggers to learn more.
 */
export class OrganizationJobTrigger extends pulumi.CustomResource {
    /**
     * Get an existing OrganizationJobTrigger resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): OrganizationJobTrigger {
        return new OrganizationJobTrigger(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'google-cloud:dlp/v2:OrganizationJobTrigger';

    /**
     * Returns true if the given object is an instance of OrganizationJobTrigger.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrganizationJobTrigger {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrganizationJobTrigger.__pulumiType;
    }


    /**
     * Create a OrganizationJobTrigger resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrganizationJobTriggerArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.jobTriggersId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'jobTriggersId'");
            }
            if ((!args || args.locationsId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'locationsId'");
            }
            if ((!args || args.organizationsId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'organizationsId'");
            }
            inputs["jobTrigger"] = args ? args.jobTrigger : undefined;
            inputs["jobTriggersId"] = args ? args.jobTriggersId : undefined;
            inputs["locationId"] = args ? args.locationId : undefined;
            inputs["locationsId"] = args ? args.locationsId : undefined;
            inputs["organizationsId"] = args ? args.organizationsId : undefined;
            inputs["triggerId"] = args ? args.triggerId : undefined;
        } else {
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(OrganizationJobTrigger.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a OrganizationJobTrigger resource.
 */
export interface OrganizationJobTriggerArgs {
    /**
     * Required. The JobTrigger to create.
     */
    readonly jobTrigger?: pulumi.Input<inputs.dlp.v2.GooglePrivacyDlpV2JobTrigger>;
    readonly jobTriggersId: pulumi.Input<string>;
    /**
     * Deprecated. This field has no effect.
     */
    readonly locationId?: pulumi.Input<string>;
    readonly locationsId: pulumi.Input<string>;
    readonly organizationsId: pulumi.Input<string>;
    /**
     * The trigger id can contain uppercase and lowercase letters, numbers, and hyphens; that is, it must match the regular expression: `[a-zA-Z\d-_]+`. The maximum length is 100 characters. Can be empty to allow the system to generate one.
     */
    readonly triggerId?: pulumi.Input<string>;
}
