// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.Ml.V1.Outputs
{

    [OutputType]
    public sealed class GoogleCloudMlV1__SampledShapleyAttributionResponse
    {
        /// <summary>
        /// The number of feature permutations to consider when approximating the Shapley values.
        /// </summary>
        public readonly int NumPaths;

        [OutputConstructor]
        private GoogleCloudMlV1__SampledShapleyAttributionResponse(int numPaths)
        {
            NumPaths = numPaths;
        }
    }
}
