// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.googlenative.billingbudgets.v1.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.googlenative.billingbudgets.v1.outputs.GoogleCloudBillingBudgetsV1LastPeriodAmountResponse;
import com.pulumi.googlenative.billingbudgets.v1.outputs.GoogleTypeMoneyResponse;
import java.util.Objects;

@CustomType
public final class GoogleCloudBillingBudgetsV1BudgetAmountResponse {
    /**
     * @return Use the last period&#39;s actual spend as the budget for the present period. LastPeriodAmount can only be set when the budget&#39;s time period is a Filter.calendar_period. It cannot be set in combination with Filter.custom_period.
     * 
     */
    private GoogleCloudBillingBudgetsV1LastPeriodAmountResponse lastPeriodAmount;
    /**
     * @return A specified amount to use as the budget. `currency_code` is optional. If specified when creating a budget, it must match the currency of the billing account. If specified when updating a budget, it must match the currency_code of the existing budget. The `currency_code` is provided on output.
     * 
     */
    private GoogleTypeMoneyResponse specifiedAmount;

    private GoogleCloudBillingBudgetsV1BudgetAmountResponse() {}
    /**
     * @return Use the last period&#39;s actual spend as the budget for the present period. LastPeriodAmount can only be set when the budget&#39;s time period is a Filter.calendar_period. It cannot be set in combination with Filter.custom_period.
     * 
     */
    public GoogleCloudBillingBudgetsV1LastPeriodAmountResponse lastPeriodAmount() {
        return this.lastPeriodAmount;
    }
    /**
     * @return A specified amount to use as the budget. `currency_code` is optional. If specified when creating a budget, it must match the currency of the billing account. If specified when updating a budget, it must match the currency_code of the existing budget. The `currency_code` is provided on output.
     * 
     */
    public GoogleTypeMoneyResponse specifiedAmount() {
        return this.specifiedAmount;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GoogleCloudBillingBudgetsV1BudgetAmountResponse defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GoogleCloudBillingBudgetsV1LastPeriodAmountResponse lastPeriodAmount;
        private GoogleTypeMoneyResponse specifiedAmount;
        public Builder() {}
        public Builder(GoogleCloudBillingBudgetsV1BudgetAmountResponse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.lastPeriodAmount = defaults.lastPeriodAmount;
    	      this.specifiedAmount = defaults.specifiedAmount;
        }

        @CustomType.Setter
        public Builder lastPeriodAmount(GoogleCloudBillingBudgetsV1LastPeriodAmountResponse lastPeriodAmount) {
            this.lastPeriodAmount = Objects.requireNonNull(lastPeriodAmount);
            return this;
        }
        @CustomType.Setter
        public Builder specifiedAmount(GoogleTypeMoneyResponse specifiedAmount) {
            this.specifiedAmount = Objects.requireNonNull(specifiedAmount);
            return this;
        }
        public GoogleCloudBillingBudgetsV1BudgetAmountResponse build() {
            final var o = new GoogleCloudBillingBudgetsV1BudgetAmountResponse();
            o.lastPeriodAmount = lastPeriodAmount;
            o.specifiedAmount = specifiedAmount;
            return o;
        }
    }
}
