// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.Apigee.V1
{
    public static class GetSubscription
    {
        /// <summary>
        /// Gets details for an API product subscription.
        /// </summary>
        public static Task<GetSubscriptionResult> InvokeAsync(GetSubscriptionArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetSubscriptionResult>("google-native:apigee/v1:getSubscription", args ?? new GetSubscriptionArgs(), options.WithDefaults());

        /// <summary>
        /// Gets details for an API product subscription.
        /// </summary>
        public static Output<GetSubscriptionResult> Invoke(GetSubscriptionInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetSubscriptionResult>("google-native:apigee/v1:getSubscription", args ?? new GetSubscriptionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSubscriptionArgs : global::Pulumi.InvokeArgs
    {
        [Input("developerId", required: true)]
        public string DeveloperId { get; set; } = null!;

        [Input("organizationId", required: true)]
        public string OrganizationId { get; set; } = null!;

        [Input("subscriptionId", required: true)]
        public string SubscriptionId { get; set; } = null!;

        public GetSubscriptionArgs()
        {
        }
        public static new GetSubscriptionArgs Empty => new GetSubscriptionArgs();
    }

    public sealed class GetSubscriptionInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("developerId", required: true)]
        public Input<string> DeveloperId { get; set; } = null!;

        [Input("organizationId", required: true)]
        public Input<string> OrganizationId { get; set; } = null!;

        [Input("subscriptionId", required: true)]
        public Input<string> SubscriptionId { get; set; } = null!;

        public GetSubscriptionInvokeArgs()
        {
        }
        public static new GetSubscriptionInvokeArgs Empty => new GetSubscriptionInvokeArgs();
    }


    [OutputType]
    public sealed class GetSubscriptionResult
    {
        /// <summary>
        /// Name of the API product for which the developer is purchasing a subscription.
        /// </summary>
        public readonly string Apiproduct;
        /// <summary>
        /// Time when the API product subscription was created in milliseconds since epoch.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Time when the API product subscription ends in milliseconds since epoch.
        /// </summary>
        public readonly string EndTime;
        /// <summary>
        /// Time when the API product subscription was last modified in milliseconds since epoch.
        /// </summary>
        public readonly string LastModifiedAt;
        /// <summary>
        /// Name of the API product subscription.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Time when the API product subscription starts in milliseconds since epoch.
        /// </summary>
        public readonly string StartTime;

        [OutputConstructor]
        private GetSubscriptionResult(
            string apiproduct,

            string createdAt,

            string endTime,

            string lastModifiedAt,

            string name,

            string startTime)
        {
            Apiproduct = apiproduct;
            CreatedAt = createdAt;
            EndTime = endTime;
            LastModifiedAt = lastModifiedAt;
            Name = name;
            StartTime = startTime;
        }
    }
}
