// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.Dialogflow.V3.Outputs
{

    /// <summary>
    /// Text input which can be used for prompt or banned phrases.
    /// </summary>
    [OutputType]
    public sealed class GoogleCloudDialogflowCxV3PhraseResponse
    {
        /// <summary>
        /// Text input which can be used for prompt or banned phrases.
        /// </summary>
        public readonly string Text;

        [OutputConstructor]
        private GoogleCloudDialogflowCxV3PhraseResponse(string text)
        {
            Text = text;
        }
    }
}
