// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.Integrations.V1.Outputs
{

    /// <summary>
    /// Range used to validate doubles and floats.
    /// </summary>
    [OutputType]
    public sealed class EnterpriseCrmEventbusProtoParamSpecEntryValidationRuleDoubleRangeResponse
    {
        /// <summary>
        /// The inclusive maximum of the acceptable range.
        /// </summary>
        public readonly double Max;
        /// <summary>
        /// The inclusive minimum of the acceptable range.
        /// </summary>
        public readonly double Min;

        [OutputConstructor]
        private EnterpriseCrmEventbusProtoParamSpecEntryValidationRuleDoubleRangeResponse(
            double max,

            double min)
        {
            Max = max;
            Min = min;
        }
    }
}
