// Code generated by the Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1beta1

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	iam "github.com/pulumi/pulumi-google-native/sdk/go/google/iam/v1"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// TODO
type ReusableConfigIamBinding struct {
	pulumi.CustomResourceState

	// An IAM Condition for a given binding. See https://cloud.google.com/iam/docs/conditions-overview for additional details.
	Condition iam.ConditionPtrOutput `pulumi:"condition"`
	// The etag of the resource's IAM policy.
	Etag pulumi.StringOutput `pulumi:"etag"`
	// Identities that will be granted the privilege in role. Each entry can have one of the following values:
	//
	//  * user:{emailid}: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.
	//  * serviceAccount:{emailid}: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.
	//  * group:{emailid}: An email address that represents a Google group. For example, admins@example.com.
	//  * domain:{domain}: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
	Members pulumi.StringArrayOutput `pulumi:"members"`
	// The name of the resource to manage IAM policies for.
	Name pulumi.StringOutput `pulumi:"name"`
	// The project in which the resource belongs. If it is not provided, a default will be supplied.
	Project pulumi.StringOutput `pulumi:"project"`
	// The role that should be applied. Only one `IamBinding` can be used per role.
	Role pulumi.StringOutput `pulumi:"role"`
}

// NewReusableConfigIamBinding registers a new resource with the given unique name, arguments, and options.
func NewReusableConfigIamBinding(ctx *pulumi.Context,
	name string, args *ReusableConfigIamBindingArgs, opts ...pulumi.ResourceOption) (*ReusableConfigIamBinding, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Members == nil {
		return nil, errors.New("invalid value for required argument 'Members'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Role == nil {
		return nil, errors.New("invalid value for required argument 'Role'")
	}
	var resource ReusableConfigIamBinding
	err := ctx.RegisterResource("google-native:privateca/v1beta1:ReusableConfigIamBinding", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetReusableConfigIamBinding gets an existing ReusableConfigIamBinding resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetReusableConfigIamBinding(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ReusableConfigIamBindingState, opts ...pulumi.ResourceOption) (*ReusableConfigIamBinding, error) {
	var resource ReusableConfigIamBinding
	err := ctx.ReadResource("google-native:privateca/v1beta1:ReusableConfigIamBinding", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ReusableConfigIamBinding resources.
type reusableConfigIamBindingState struct {
}

type ReusableConfigIamBindingState struct {
}

func (ReusableConfigIamBindingState) ElementType() reflect.Type {
	return reflect.TypeOf((*reusableConfigIamBindingState)(nil)).Elem()
}

type reusableConfigIamBindingArgs struct {
	// An IAM Condition for a given binding.
	Condition *iam.Condition `pulumi:"condition"`
	// Identities that will be granted the privilege in role. Each entry can have one of the following values:
	//
	//  * user:{emailid}: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.
	//  * serviceAccount:{emailid}: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.
	//  * group:{emailid}: An email address that represents a Google group. For example, admins@example.com.
	//  * domain:{domain}: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
	Members []string `pulumi:"members"`
	// The name of the resource to manage IAM policies for.
	Name string `pulumi:"name"`
	// The role that should be applied. Only one `IamBinding` can be used per role.
	Role string `pulumi:"role"`
}

// The set of arguments for constructing a ReusableConfigIamBinding resource.
type ReusableConfigIamBindingArgs struct {
	// An IAM Condition for a given binding.
	Condition iam.ConditionPtrInput
	// Identities that will be granted the privilege in role. Each entry can have one of the following values:
	//
	//  * user:{emailid}: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.
	//  * serviceAccount:{emailid}: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.
	//  * group:{emailid}: An email address that represents a Google group. For example, admins@example.com.
	//  * domain:{domain}: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
	Members pulumi.StringArrayInput
	// The name of the resource to manage IAM policies for.
	Name pulumi.StringInput
	// The role that should be applied. Only one `IamBinding` can be used per role.
	Role pulumi.StringInput
}

func (ReusableConfigIamBindingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*reusableConfigIamBindingArgs)(nil)).Elem()
}

type ReusableConfigIamBindingInput interface {
	pulumi.Input

	ToReusableConfigIamBindingOutput() ReusableConfigIamBindingOutput
	ToReusableConfigIamBindingOutputWithContext(ctx context.Context) ReusableConfigIamBindingOutput
}

func (*ReusableConfigIamBinding) ElementType() reflect.Type {
	return reflect.TypeOf((**ReusableConfigIamBinding)(nil)).Elem()
}

func (i *ReusableConfigIamBinding) ToReusableConfigIamBindingOutput() ReusableConfigIamBindingOutput {
	return i.ToReusableConfigIamBindingOutputWithContext(context.Background())
}

func (i *ReusableConfigIamBinding) ToReusableConfigIamBindingOutputWithContext(ctx context.Context) ReusableConfigIamBindingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReusableConfigIamBindingOutput)
}

type ReusableConfigIamBindingOutput struct{ *pulumi.OutputState }

func (ReusableConfigIamBindingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ReusableConfigIamBinding)(nil)).Elem()
}

func (o ReusableConfigIamBindingOutput) ToReusableConfigIamBindingOutput() ReusableConfigIamBindingOutput {
	return o
}

func (o ReusableConfigIamBindingOutput) ToReusableConfigIamBindingOutputWithContext(ctx context.Context) ReusableConfigIamBindingOutput {
	return o
}

// An IAM Condition for a given binding. See https://cloud.google.com/iam/docs/conditions-overview for additional details.
func (o ReusableConfigIamBindingOutput) Condition() iam.ConditionPtrOutput {
	return o.ApplyT(func(v *ReusableConfigIamBinding) iam.ConditionPtrOutput { return v.Condition }).(iam.ConditionPtrOutput)
}

// The etag of the resource's IAM policy.
func (o ReusableConfigIamBindingOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v *ReusableConfigIamBinding) pulumi.StringOutput { return v.Etag }).(pulumi.StringOutput)
}

// Identities that will be granted the privilege in role. Each entry can have one of the following values:
//
//   - user:{emailid}: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.
//   - serviceAccount:{emailid}: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.
//   - group:{emailid}: An email address that represents a Google group. For example, admins@example.com.
//   - domain:{domain}: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
func (o ReusableConfigIamBindingOutput) Members() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ReusableConfigIamBinding) pulumi.StringArrayOutput { return v.Members }).(pulumi.StringArrayOutput)
}

// The name of the resource to manage IAM policies for.
func (o ReusableConfigIamBindingOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ReusableConfigIamBinding) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The project in which the resource belongs. If it is not provided, a default will be supplied.
func (o ReusableConfigIamBindingOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *ReusableConfigIamBinding) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// The role that should be applied. Only one `IamBinding` can be used per role.
func (o ReusableConfigIamBindingOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v *ReusableConfigIamBinding) pulumi.StringOutput { return v.Role }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ReusableConfigIamBindingInput)(nil)).Elem(), &ReusableConfigIamBinding{})
	pulumi.RegisterOutputType(ReusableConfigIamBindingOutput{})
}
