// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../../types";
import * as utilities from "../../utilities";

/**
 * Creates a new `Occurrence`. Use this method to create `Occurrences` for a resource.
 */
export class Occurrence extends pulumi.CustomResource {
    /**
     * Get an existing Occurrence resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Occurrence {
        return new Occurrence(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'google-native:containeranalysis/v1alpha1:Occurrence';

    /**
     * Returns true if the given object is an instance of Occurrence.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Occurrence {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Occurrence.__pulumiType;
    }

    /**
     * Describes an attestation of an artifact.
     */
    public readonly attestation!: pulumi.Output<outputs.containeranalysis.v1alpha1.AttestationResponse>;
    /**
     * Build details for a verifiable build.
     */
    public readonly buildDetails!: pulumi.Output<outputs.containeranalysis.v1alpha1.BuildDetailsResponse>;
    /**
     * Describes whether or not a resource passes compliance checks.
     */
    public readonly compliance!: pulumi.Output<outputs.containeranalysis.v1alpha1.ComplianceOccurrenceResponse>;
    /**
     * The time this `Occurrence` was created.
     */
    public /*out*/ readonly createTime!: pulumi.Output<string>;
    /**
     * Describes the deployment of an artifact on a runtime.
     */
    public readonly deployment!: pulumi.Output<outputs.containeranalysis.v1alpha1.DeploymentResponse>;
    /**
     * Describes how this resource derives from the basis in the associated note.
     */
    public readonly derivedImage!: pulumi.Output<outputs.containeranalysis.v1alpha1.DerivedResponse>;
    /**
     * Describes the initial scan status for this resource.
     */
    public readonly discovered!: pulumi.Output<outputs.containeranalysis.v1alpha1.DiscoveredResponse>;
    /**
     * This represents a DSSE attestation occurrence
     */
    public readonly dsseAttestation!: pulumi.Output<outputs.containeranalysis.v1alpha1.DSSEAttestationOccurrenceResponse>;
    /**
     * https://github.com/secure-systems-lab/dsse
     */
    public readonly envelope!: pulumi.Output<outputs.containeranalysis.v1alpha1.EnvelopeResponse>;
    /**
     * Describes the installation of a package on the linked resource.
     */
    public readonly installation!: pulumi.Output<outputs.containeranalysis.v1alpha1.InstallationResponse>;
    /**
     * This explicitly denotes which of the `Occurrence` details are specified. This field can be used as a filter in list requests.
     */
    public /*out*/ readonly kind!: pulumi.Output<string>;
    /**
     * The name of the `Occurrence` in the form "projects/{project_id}/occurrences/{OCCURRENCE_ID}"
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * An analysis note associated with this image, in the form "providers/{provider_id}/notes/{NOTE_ID}" This field can be used as a filter in list requests.
     */
    public readonly noteName!: pulumi.Output<string>;
    /**
     * A description of actions that can be taken to remedy the `Note`
     */
    public readonly remediation!: pulumi.Output<string>;
    /**
     *  The resource for which the `Occurrence` applies.
     */
    public readonly resource!: pulumi.Output<outputs.containeranalysis.v1alpha1.ResourceResponse>;
    /**
     * The unique URL of the image or the container for which the `Occurrence` applies. For example, https://gcr.io/project/image@sha256:foo This field can be used as a filter in list requests.
     */
    public readonly resourceUrl!: pulumi.Output<string>;
    /**
     * Describes a specific software bill of materials document.
     */
    public readonly sbom!: pulumi.Output<outputs.containeranalysis.v1alpha1.DocumentOccurrenceResponse>;
    /**
     * Describes a specific SPDX File.
     */
    public readonly spdxFile!: pulumi.Output<outputs.containeranalysis.v1alpha1.FileOccurrenceResponse>;
    /**
     * Describes a specific SPDX Package.
     */
    public readonly spdxPackage!: pulumi.Output<outputs.containeranalysis.v1alpha1.PackageInfoOccurrenceResponse>;
    /**
     * Describes a specific relationship between SPDX elements.
     */
    public readonly spdxRelationship!: pulumi.Output<outputs.containeranalysis.v1alpha1.RelationshipOccurrenceResponse>;
    /**
     * The time this `Occurrence` was last updated.
     */
    public /*out*/ readonly updateTime!: pulumi.Output<string>;
    /**
     * Describes an upgrade.
     */
    public readonly upgrade!: pulumi.Output<outputs.containeranalysis.v1alpha1.UpgradeOccurrenceResponse>;
    /**
     * Details of a security vulnerability note.
     */
    public readonly vulnerabilityDetails!: pulumi.Output<outputs.containeranalysis.v1alpha1.VulnerabilityDetailsResponse>;

    /**
     * Create a Occurrence resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: OccurrenceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["attestation"] = args ? args.attestation : undefined;
            resourceInputs["buildDetails"] = args ? args.buildDetails : undefined;
            resourceInputs["compliance"] = args ? args.compliance : undefined;
            resourceInputs["deployment"] = args ? args.deployment : undefined;
            resourceInputs["derivedImage"] = args ? args.derivedImage : undefined;
            resourceInputs["discovered"] = args ? args.discovered : undefined;
            resourceInputs["dsseAttestation"] = args ? args.dsseAttestation : undefined;
            resourceInputs["envelope"] = args ? args.envelope : undefined;
            resourceInputs["installation"] = args ? args.installation : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["noteName"] = args ? args.noteName : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["remediation"] = args ? args.remediation : undefined;
            resourceInputs["resource"] = args ? args.resource : undefined;
            resourceInputs["resourceUrl"] = args ? args.resourceUrl : undefined;
            resourceInputs["sbom"] = args ? args.sbom : undefined;
            resourceInputs["spdxFile"] = args ? args.spdxFile : undefined;
            resourceInputs["spdxPackage"] = args ? args.spdxPackage : undefined;
            resourceInputs["spdxRelationship"] = args ? args.spdxRelationship : undefined;
            resourceInputs["upgrade"] = args ? args.upgrade : undefined;
            resourceInputs["vulnerabilityDetails"] = args ? args.vulnerabilityDetails : undefined;
            resourceInputs["createTime"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["updateTime"] = undefined /*out*/;
        } else {
            resourceInputs["attestation"] = undefined /*out*/;
            resourceInputs["buildDetails"] = undefined /*out*/;
            resourceInputs["compliance"] = undefined /*out*/;
            resourceInputs["createTime"] = undefined /*out*/;
            resourceInputs["deployment"] = undefined /*out*/;
            resourceInputs["derivedImage"] = undefined /*out*/;
            resourceInputs["discovered"] = undefined /*out*/;
            resourceInputs["dsseAttestation"] = undefined /*out*/;
            resourceInputs["envelope"] = undefined /*out*/;
            resourceInputs["installation"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["noteName"] = undefined /*out*/;
            resourceInputs["remediation"] = undefined /*out*/;
            resourceInputs["resource"] = undefined /*out*/;
            resourceInputs["resourceUrl"] = undefined /*out*/;
            resourceInputs["sbom"] = undefined /*out*/;
            resourceInputs["spdxFile"] = undefined /*out*/;
            resourceInputs["spdxPackage"] = undefined /*out*/;
            resourceInputs["spdxRelationship"] = undefined /*out*/;
            resourceInputs["updateTime"] = undefined /*out*/;
            resourceInputs["upgrade"] = undefined /*out*/;
            resourceInputs["vulnerabilityDetails"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Occurrence.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Occurrence resource.
 */
export interface OccurrenceArgs {
    /**
     * Describes an attestation of an artifact.
     */
    attestation?: pulumi.Input<inputs.containeranalysis.v1alpha1.AttestationArgs>;
    /**
     * Build details for a verifiable build.
     */
    buildDetails?: pulumi.Input<inputs.containeranalysis.v1alpha1.BuildDetailsArgs>;
    /**
     * Describes whether or not a resource passes compliance checks.
     */
    compliance?: pulumi.Input<inputs.containeranalysis.v1alpha1.ComplianceOccurrenceArgs>;
    /**
     * Describes the deployment of an artifact on a runtime.
     */
    deployment?: pulumi.Input<inputs.containeranalysis.v1alpha1.DeploymentArgs>;
    /**
     * Describes how this resource derives from the basis in the associated note.
     */
    derivedImage?: pulumi.Input<inputs.containeranalysis.v1alpha1.DerivedArgs>;
    /**
     * Describes the initial scan status for this resource.
     */
    discovered?: pulumi.Input<inputs.containeranalysis.v1alpha1.DiscoveredArgs>;
    /**
     * This represents a DSSE attestation occurrence
     */
    dsseAttestation?: pulumi.Input<inputs.containeranalysis.v1alpha1.DSSEAttestationOccurrenceArgs>;
    /**
     * https://github.com/secure-systems-lab/dsse
     */
    envelope?: pulumi.Input<inputs.containeranalysis.v1alpha1.EnvelopeArgs>;
    /**
     * Describes the installation of a package on the linked resource.
     */
    installation?: pulumi.Input<inputs.containeranalysis.v1alpha1.InstallationArgs>;
    name?: pulumi.Input<string>;
    /**
     * An analysis note associated with this image, in the form "providers/{provider_id}/notes/{NOTE_ID}" This field can be used as a filter in list requests.
     */
    noteName?: pulumi.Input<string>;
    project?: pulumi.Input<string>;
    /**
     * A description of actions that can be taken to remedy the `Note`
     */
    remediation?: pulumi.Input<string>;
    /**
     *  The resource for which the `Occurrence` applies.
     */
    resource?: pulumi.Input<inputs.containeranalysis.v1alpha1.ResourceArgs>;
    /**
     * The unique URL of the image or the container for which the `Occurrence` applies. For example, https://gcr.io/project/image@sha256:foo This field can be used as a filter in list requests.
     */
    resourceUrl?: pulumi.Input<string>;
    /**
     * Describes a specific software bill of materials document.
     */
    sbom?: pulumi.Input<inputs.containeranalysis.v1alpha1.DocumentOccurrenceArgs>;
    /**
     * Describes a specific SPDX File.
     */
    spdxFile?: pulumi.Input<inputs.containeranalysis.v1alpha1.FileOccurrenceArgs>;
    /**
     * Describes a specific SPDX Package.
     */
    spdxPackage?: pulumi.Input<inputs.containeranalysis.v1alpha1.PackageInfoOccurrenceArgs>;
    /**
     * Describes a specific relationship between SPDX elements.
     */
    spdxRelationship?: pulumi.Input<inputs.containeranalysis.v1alpha1.RelationshipOccurrenceArgs>;
    /**
     * Describes an upgrade.
     */
    upgrade?: pulumi.Input<inputs.containeranalysis.v1alpha1.UpgradeOccurrenceArgs>;
    /**
     * Details of a security vulnerability note.
     */
    vulnerabilityDetails?: pulumi.Input<inputs.containeranalysis.v1alpha1.VulnerabilityDetailsArgs>;
}
