// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GcpNative.Container.V1.Inputs
{

    /// <summary>
    /// Autopilot is the configuration for Autopilot settings on the cluster.
    /// </summary>
    public sealed class AutopilotArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable Autopilot
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        public AutopilotArgs()
        {
        }
    }
}
