// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleCloud.Dlp.V2
{
    /// <summary>
    /// Creates a new job to inspect storage or calculate risk metrics. See https://cloud.google.com/dlp/docs/inspecting-storage and https://cloud.google.com/dlp/docs/compute-risk-analysis to learn more. When no InfoTypes or CustomInfoTypes are specified in inspect jobs, the system will automatically choose what detectors to run. By default this may be all types, but may change over time as detectors are updated.
    /// </summary>
    [GoogleCloudResourceType("google-cloud:dlp/v2:GooglePrivacyDlpV2DlpJob")]
    public partial class GooglePrivacyDlpV2DlpJob : Pulumi.CustomResource
    {
        /// <summary>
        /// Create a GooglePrivacyDlpV2DlpJob resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GooglePrivacyDlpV2DlpJob(string name, GooglePrivacyDlpV2DlpJobArgs args, CustomResourceOptions? options = null)
            : base("google-cloud:dlp/v2:GooglePrivacyDlpV2DlpJob", name, args ?? new GooglePrivacyDlpV2DlpJobArgs(), MakeResourceOptions(options, ""))
        {
        }

        private GooglePrivacyDlpV2DlpJob(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("google-cloud:dlp/v2:GooglePrivacyDlpV2DlpJob", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing GooglePrivacyDlpV2DlpJob resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static GooglePrivacyDlpV2DlpJob Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new GooglePrivacyDlpV2DlpJob(name, id, options);
        }
    }

    public sealed class GooglePrivacyDlpV2DlpJobArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// An inspection job scans a storage repository for InfoTypes.
        /// </summary>
        [Input("inspectJob")]
        public Input<Inputs.GooglePrivacyDlpV2InspectJobConfigArgs>? InspectJob { get; set; }

        /// <summary>
        /// The job id can contain uppercase and lowercase letters, numbers, and hyphens; that is, it must match the regular expression: `[a-zA-Z\d-_]+`. The maximum length is 100 characters. Can be empty to allow the system to generate one.
        /// </summary>
        [Input("jobId")]
        public Input<string>? JobId { get; set; }

        /// <summary>
        /// Deprecated. This field has no effect.
        /// </summary>
        [Input("locationId")]
        public Input<string>? LocationId { get; set; }

        /// <summary>
        /// Required. Parent resource name. The format of this value varies depending on whether you have [specified a processing location](https://cloud.google.com/dlp/docs/specifying-location): + Projects scope, location specified: `projects/`PROJECT_ID`/locations/`LOCATION_ID + Projects scope, no location specified (defaults to global): `projects/`PROJECT_ID The following example `parent` string specifies a parent project with the identifier `example-project`, and specifies the `europe-west3` location for processing data: parent=projects/example-project/locations/europe-west3
        /// </summary>
        [Input("parent", required: true)]
        public Input<string> Parent { get; set; } = null!;

        /// <summary>
        /// A risk analysis job calculates re-identification risk metrics for a BigQuery table.
        /// </summary>
        [Input("riskJob")]
        public Input<Inputs.GooglePrivacyDlpV2RiskAnalysisJobConfigArgs>? RiskJob { get; set; }

        public GooglePrivacyDlpV2DlpJobArgs()
        {
        }
    }
}
