// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.VMMigration.V1.Outputs
{

    /// <summary>
    /// ComputeEngineDisksTargetDefaults is a collection of details for creating Persistent Disks in a target Compute Engine project.
    /// </summary>
    [OutputType]
    public sealed class ComputeEngineDisksTargetDefaultsResponse
    {
        /// <summary>
        /// The details of each Persistent Disk to create.
        /// </summary>
        public readonly ImmutableArray<Outputs.PersistentDiskDefaultsResponse> Disks;
        /// <summary>
        /// Details of the disk only migration target.
        /// </summary>
        public readonly Outputs.DisksMigrationDisksTargetDefaultsResponse DisksTargetDefaults;
        /// <summary>
        /// The full path of the resource of type TargetProject which represents the Compute Engine project in which to create the Persistent Disks.
        /// </summary>
        public readonly string TargetProject;
        /// <summary>
        /// Details of the VM migration target.
        /// </summary>
        public readonly Outputs.DisksMigrationVmTargetDefaultsResponse VmTargetDefaults;
        /// <summary>
        /// The zone in which to create the Persistent Disks.
        /// </summary>
        public readonly string Zone;

        [OutputConstructor]
        private ComputeEngineDisksTargetDefaultsResponse(
            ImmutableArray<Outputs.PersistentDiskDefaultsResponse> disks,

            Outputs.DisksMigrationDisksTargetDefaultsResponse disksTargetDefaults,

            string targetProject,

            Outputs.DisksMigrationVmTargetDefaultsResponse vmTargetDefaults,

            string zone)
        {
            Disks = disks;
            DisksTargetDefaults = disksTargetDefaults;
            TargetProject = targetProject;
            VmTargetDefaults = vmTargetDefaults;
            Zone = zone;
        }
    }
}
