// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleCloud.DataFusion.V1.Inputs
{

    /// <summary>
    /// Identifies Data Fusion accelerators for an instance.
    /// </summary>
    public sealed class AcceleratorArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The type of an accelator for a CDF instance.
        /// </summary>
        [Input("acceleratorType")]
        public Input<string>? AcceleratorType { get; set; }

        /// <summary>
        /// The state of the accelerator
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        public AcceleratorArgs()
        {
        }
    }
}
