// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.GKEHub.V1Alpha.Outputs
{

    /// <summary>
    /// NamespaceLifecycleState describes the state of a Namespace resource.
    /// </summary>
    [OutputType]
    public sealed class NamespaceLifecycleStateResponse
    {
        /// <summary>
        /// The current state of the Namespace resource.
        /// </summary>
        public readonly string Code;

        [OutputConstructor]
        private NamespaceLifecycleStateResponse(string code)
        {
            Code = code;
        }
    }
}
