{
  "canonicalName": "Cloud Identity",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "name": "cloudidentity",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "id": "cloudidentity:v1beta1",
  "batchPath": "batch",
  "version": "v1beta1",
  "resources": {
    "devices": {
      "resources": {
        "deviceUsers": {
          "resources": {
            "clientStates": {
              "methods": {
                "patch": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "path": "v1beta1/{+name}",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "PATCH"
                },
                "get": {
                  "description": "Gets the client state for the device user",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "httpMethod": "GET",
                  "path": "v1beta1/{+name}",
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}"
                }
              }
            }
          },
          "methods": {
            "lookup": {
              "path": "v1beta1/{+parent}:lookup",
              "httpMethod": "GET",
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers:lookup"
            },
            "wipe": {
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "description": "Wipes the user's account on a device.",
              "httpMethod": "POST",
              "path": "v1beta1/{+name}:wipe"
            },
            "get": {
              "httpMethod": "GET",
              "id": "cloudidentity.devices.deviceUsers.get",
              "path": "v1beta1/{+name}",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "description": "Retrieves the specified DeviceUser"
            },
            "block": {
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "httpMethod": "POST",
              "path": "v1beta1/{+name}:block",
              "description": "Blocks device from accessing user data",
              "id": "cloudidentity.devices.deviceUsers.block"
            },
            "approve": {
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "id": "cloudidentity.devices.deviceUsers.approve",
              "path": "v1beta1/{+name}:approve",
              "description": "Approves device to access user data.",
              "httpMethod": "POST"
            },
            "delete": {
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "path": "v1beta1/{+name}",
              "httpMethod": "DELETE"
            },
            "list": {
              "path": "v1beta1/{+parent}/deviceUsers",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers",
              "description": "Lists/Searches DeviceUsers.",
              "id": "cloudidentity.devices.deviceUsers.list",
              "httpMethod": "GET"
            },
            "cancelWipe": {
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "httpMethod": "POST",
              "path": "v1beta1/{+name}:cancelWipe"
            }
          }
        }
      },
      "methods": {
        "create": {
          "path": "v1beta1/devices",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "flatPath": "v1beta1/devices",
          "id": "cloudidentity.devices.create",
          "httpMethod": "POST"
        },
        "delete": {
          "path": "v1beta1/{+name}",
          "httpMethod": "DELETE",
          "id": "cloudidentity.devices.delete",
          "description": "Deletes the specified device.",
          "flatPath": "v1beta1/devices/{devicesId}"
        },
        "get": {
          "path": "v1beta1/{+name}",
          "httpMethod": "GET",
          "description": "Retrieves the specified device.",
          "flatPath": "v1beta1/devices/{devicesId}",
          "id": "cloudidentity.devices.get"
        },
        "cancelWipe": {
          "id": "cloudidentity.devices.cancelWipe",
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
          "httpMethod": "POST",
          "flatPath": "v1beta1/devices/{devicesId}:cancelWipe",
          "path": "v1beta1/{+name}:cancelWipe"
        },
        "wipe": {
          "flatPath": "v1beta1/devices/{devicesId}:wipe",
          "description": "Wipes all data on the specified device.",
          "path": "v1beta1/{+name}:wipe",
          "httpMethod": "POST",
          "id": "cloudidentity.devices.wipe"
        },
        "list": {
          "description": "Lists/Searches devices.",
          "path": "v1beta1/devices",
          "flatPath": "v1beta1/devices",
          "id": "cloudidentity.devices.list",
          "httpMethod": "GET"
        }
      }
    },
    "groups": {
      "methods": {
        "delete": {
          "path": "v1beta1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.delete",
          "flatPath": "v1beta1/groups/{groupsId}",
          "httpMethod": "DELETE",
          "description": "Deletes a `Group`."
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1beta1/groups/{groupsId}",
          "path": "v1beta1/{+name}",
          "description": "Updates a `Group`.",
          "id": "cloudidentity.groups.patch"
        },
        "create": {
          "flatPath": "v1beta1/groups",
          "id": "cloudidentity.groups.create",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1beta1/groups",
          "description": "Creates a `Group`.",
          "httpMethod": "POST"
        },
        "list": {
          "id": "cloudidentity.groups.list",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1beta1/groups",
          "httpMethod": "GET",
          "description": "Lists the `Group`s under a customer or namespace.",
          "flatPath": "v1beta1/groups"
        },
        "lookup": {
          "id": "cloudidentity.groups.lookup",
          "path": "v1beta1/groups:lookup",
          "httpMethod": "GET",
          "flatPath": "v1beta1/groups:lookup",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`."
        },
        "get": {
          "description": "Retrieves a `Group`.",
          "id": "cloudidentity.groups.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/groups/{groupsId}"
        },
        "search": {
          "flatPath": "v1beta1/groups:search",
          "httpMethod": "GET",
          "id": "cloudidentity.groups.search",
          "description": "Searches for `Group`s matching a specified query.",
          "path": "v1beta1/groups:search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        }
      },
      "resources": {
        "memberships": {
          "methods": {
            "searchTransitiveMemberships": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "path": "v1beta1/{+parent}/memberships:searchTransitiveMemberships",
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "httpMethod": "GET"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Retrieves a `Membership`.",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "path": "v1beta1/{+name}",
              "id": "cloudidentity.groups.memberships.get",
              "httpMethod": "GET"
            },
            "searchTransitiveGroups": {
              "httpMethod": "GET",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "path": "v1beta1/{+parent}/memberships:searchTransitiveGroups",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.list",
              "path": "v1beta1/{+parent}/memberships",
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "description": "Lists the `Membership`s within a `Group`."
            },
            "getMembershipGraph": {
              "path": "v1beta1/{+parent}/memberships:getMembershipGraph",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the response will contain all membership paths between the group and the member.",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:getMembershipGraph",
              "id": "cloudidentity.groups.memberships.getMembershipGraph"
            },
            "create": {
              "id": "cloudidentity.groups.memberships.create",
              "path": "v1beta1/{+parent}/memberships",
              "httpMethod": "POST",
              "description": "Creates a `Membership`.",
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "lookup": {
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.lookup",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1beta1/{+parent}/memberships:lookup",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:lookup"
            },
            "modifyMembershipRoles": {
              "path": "v1beta1/{+name}:modifyMembershipRoles",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Modifies the `MembershipRole`s of a `Membership`."
            },
            "checkTransitiveMembership": {
              "path": "v1beta1/{+parent}/memberships:checkTransitiveMembership",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor must have view permissions to at least one transitive membership between the member and group.",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes a `Membership`.",
              "id": "cloudidentity.groups.memberships.delete",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1beta1/{+name}",
              "httpMethod": "DELETE"
            }
          }
        }
      }
    }
  },
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "title": "Cloud Identity API",
  "documentationLink": "https://cloud.google.com/identity/",
  "basePath": "",
  "version_module": true,
  "ownerName": "Google",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "description": "API for provisioning and managing identity resources.",
  "servicePath": "",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "revision": "20201213"
}
