// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.googlenative.privateca.v1beta1.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.googlenative.privateca.v1beta1.inputs.SubordinateConfigChainArgs;
import java.lang.String;
import java.util.Objects;


/**
 * Describes a subordinate CA&#39;s issuers. This is either a resource path to a known issuing CertificateAuthority, or a PEM issuer certificate chain.
 * 
 */
public final class SubordinateConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final SubordinateConfigArgs Empty = new SubordinateConfigArgs();

    /**
     * This can refer to a CertificateAuthority that was used to create a subordinate CertificateAuthority. This field is used for information and usability purposes only. The resource name is in the format `projects/*{@literal /}locations/*{@literal /}certificateAuthorities/*`.
     * 
     */
    @Import(name="certificateAuthority", required=true)
    private Output<String> certificateAuthority;

    /**
     * @return This can refer to a CertificateAuthority that was used to create a subordinate CertificateAuthority. This field is used for information and usability purposes only. The resource name is in the format `projects/*{@literal /}locations/*{@literal /}certificateAuthorities/*`.
     * 
     */
    public Output<String> certificateAuthority() {
        return this.certificateAuthority;
    }

    /**
     * Contains the PEM certificate chain for the issuers of this CertificateAuthority, but not pem certificate for this CA itself.
     * 
     */
    @Import(name="pemIssuerChain", required=true)
    private Output<SubordinateConfigChainArgs> pemIssuerChain;

    /**
     * @return Contains the PEM certificate chain for the issuers of this CertificateAuthority, but not pem certificate for this CA itself.
     * 
     */
    public Output<SubordinateConfigChainArgs> pemIssuerChain() {
        return this.pemIssuerChain;
    }

    private SubordinateConfigArgs() {}

    private SubordinateConfigArgs(SubordinateConfigArgs $) {
        this.certificateAuthority = $.certificateAuthority;
        this.pemIssuerChain = $.pemIssuerChain;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SubordinateConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SubordinateConfigArgs $;

        public Builder() {
            $ = new SubordinateConfigArgs();
        }

        public Builder(SubordinateConfigArgs defaults) {
            $ = new SubordinateConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param certificateAuthority This can refer to a CertificateAuthority that was used to create a subordinate CertificateAuthority. This field is used for information and usability purposes only. The resource name is in the format `projects/*{@literal /}locations/*{@literal /}certificateAuthorities/*`.
         * 
         * @return builder
         * 
         */
        public Builder certificateAuthority(Output<String> certificateAuthority) {
            $.certificateAuthority = certificateAuthority;
            return this;
        }

        /**
         * @param certificateAuthority This can refer to a CertificateAuthority that was used to create a subordinate CertificateAuthority. This field is used for information and usability purposes only. The resource name is in the format `projects/*{@literal /}locations/*{@literal /}certificateAuthorities/*`.
         * 
         * @return builder
         * 
         */
        public Builder certificateAuthority(String certificateAuthority) {
            return certificateAuthority(Output.of(certificateAuthority));
        }

        /**
         * @param pemIssuerChain Contains the PEM certificate chain for the issuers of this CertificateAuthority, but not pem certificate for this CA itself.
         * 
         * @return builder
         * 
         */
        public Builder pemIssuerChain(Output<SubordinateConfigChainArgs> pemIssuerChain) {
            $.pemIssuerChain = pemIssuerChain;
            return this;
        }

        /**
         * @param pemIssuerChain Contains the PEM certificate chain for the issuers of this CertificateAuthority, but not pem certificate for this CA itself.
         * 
         * @return builder
         * 
         */
        public Builder pemIssuerChain(SubordinateConfigChainArgs pemIssuerChain) {
            return pemIssuerChain(Output.of(pemIssuerChain));
        }

        public SubordinateConfigArgs build() {
            $.certificateAuthority = Objects.requireNonNull($.certificateAuthority, "expected parameter 'certificateAuthority' to be non-null");
            $.pemIssuerChain = Objects.requireNonNull($.pemIssuerChain, "expected parameter 'pemIssuerChain' to be non-null");
            return $;
        }
    }

}
