// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.DLP.V2.Outputs
{

    /// <summary>
    /// Configuration of the timespan of the items to include in scanning. Currently only supported when inspecting Cloud Storage and BigQuery.
    /// </summary>
    [OutputType]
    public sealed class GooglePrivacyDlpV2TimespanConfigResponse
    {
        /// <summary>
        /// When the job is started by a JobTrigger we will automatically figure out a valid start_time to avoid scanning files that have not been modified since the last time the JobTrigger executed. This will be based on the time of the execution of the last run of the JobTrigger or the timespan end_time used in the last run of the JobTrigger.
        /// </summary>
        public readonly bool EnableAutoPopulationOfTimespanConfig;
        /// <summary>
        /// Exclude files, tables, or rows newer than this value. If not set, no upper time limit is applied.
        /// </summary>
        public readonly string EndTime;
        /// <summary>
        /// Exclude files, tables, or rows older than this value. If not set, no lower time limit is applied.
        /// </summary>
        public readonly string StartTime;
        /// <summary>
        /// Specification of the field containing the timestamp of scanned items. Used for data sources like Datastore and BigQuery. *For BigQuery* If this value is not specified and the table was modified between the given start and end times, the entire table will be scanned. If this value is specified, then rows are filtered based on the given start and end times. Rows with a `NULL` value in the provided BigQuery column are skipped. Valid data types of the provided BigQuery column are: `INTEGER`, `DATE`, `TIMESTAMP`, and `DATETIME`. If your BigQuery table is [partitioned at ingestion time](https://cloud.google.com/bigquery/docs/partitioned-tables#ingestion_time), you can use any of the following pseudo-columns as your timestamp field. When used with Cloud DLP, these pseudo-column names are case sensitive. - _PARTITIONTIME - _PARTITIONDATE - _PARTITION_LOAD_TIME *For Datastore* If this value is specified, then entities are filtered based on the given start and end times. If an entity does not contain the provided timestamp property or contains empty or invalid values, then it is included. Valid data types of the provided timestamp property are: `TIMESTAMP`. See the [known issue](https://cloud.google.com/dlp/docs/known-issues#bq-timespan) related to this operation.
        /// </summary>
        public readonly Outputs.GooglePrivacyDlpV2FieldIdResponse TimestampField;

        [OutputConstructor]
        private GooglePrivacyDlpV2TimespanConfigResponse(
            bool enableAutoPopulationOfTimespanConfig,

            string endTime,

            string startTime,

            Outputs.GooglePrivacyDlpV2FieldIdResponse timestampField)
        {
            EnableAutoPopulationOfTimespanConfig = enableAutoPopulationOfTimespanConfig;
            EndTime = endTime;
            StartTime = startTime;
            TimestampField = timestampField;
        }
    }
}
