// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.DLP.V2.Outputs
{

    /// <summary>
    /// Set of primitive values supported by the system. Note that for the purposes of inspection or transformation, the number of bytes considered to comprise a 'Value' is based on its representation as a UTF-8 encoded string. For example, if 'integer_value' is set to 123456789, the number of bytes would be counted as 9, even though an int64 only holds up to 8 bytes of data.
    /// </summary>
    [OutputType]
    public sealed class GooglePrivacyDlpV2ValueResponse
    {
        /// <summary>
        /// boolean
        /// </summary>
        public readonly bool BooleanValue;
        /// <summary>
        /// date
        /// </summary>
        public readonly Outputs.GoogleTypeDateResponse DateValue;
        /// <summary>
        /// day of week
        /// </summary>
        public readonly string DayOfWeekValue;
        /// <summary>
        /// float
        /// </summary>
        public readonly double FloatValue;
        /// <summary>
        /// integer
        /// </summary>
        public readonly string IntegerValue;
        /// <summary>
        /// string
        /// </summary>
        public readonly string StringValue;
        /// <summary>
        /// time of day
        /// </summary>
        public readonly Outputs.GoogleTypeTimeOfDayResponse TimeValue;
        /// <summary>
        /// timestamp
        /// </summary>
        public readonly string TimestampValue;

        [OutputConstructor]
        private GooglePrivacyDlpV2ValueResponse(
            bool booleanValue,

            Outputs.GoogleTypeDateResponse dateValue,

            string dayOfWeekValue,

            double floatValue,

            string integerValue,

            string stringValue,

            Outputs.GoogleTypeTimeOfDayResponse timeValue,

            string timestampValue)
        {
            BooleanValue = booleanValue;
            DateValue = dateValue;
            DayOfWeekValue = dayOfWeekValue;
            FloatValue = floatValue;
            IntegerValue = integerValue;
            StringValue = stringValue;
            TimeValue = timeValue;
            TimestampValue = timestampValue;
        }
    }
}
