// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.googlenative.dataplex.v1.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.googlenative.dataplex.v1.outputs.GoogleCloudDataplexV1AssetDiscoveryStatusStatsResponse;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GoogleCloudDataplexV1AssetDiscoveryStatusResponse {
    /**
     * @return The duration of the last discovery run.
     * 
     */
    private String lastRunDuration;
    /**
     * @return The start time of the last discovery run.
     * 
     */
    private String lastRunTime;
    /**
     * @return Additional information about the current state.
     * 
     */
    private String message;
    /**
     * @return The current status of the discovery feature.
     * 
     */
    private String state;
    /**
     * @return Data Stats of the asset reported by discovery.
     * 
     */
    private GoogleCloudDataplexV1AssetDiscoveryStatusStatsResponse stats;
    /**
     * @return Last update time of the status.
     * 
     */
    private String updateTime;

    private GoogleCloudDataplexV1AssetDiscoveryStatusResponse() {}
    /**
     * @return The duration of the last discovery run.
     * 
     */
    public String lastRunDuration() {
        return this.lastRunDuration;
    }
    /**
     * @return The start time of the last discovery run.
     * 
     */
    public String lastRunTime() {
        return this.lastRunTime;
    }
    /**
     * @return Additional information about the current state.
     * 
     */
    public String message() {
        return this.message;
    }
    /**
     * @return The current status of the discovery feature.
     * 
     */
    public String state() {
        return this.state;
    }
    /**
     * @return Data Stats of the asset reported by discovery.
     * 
     */
    public GoogleCloudDataplexV1AssetDiscoveryStatusStatsResponse stats() {
        return this.stats;
    }
    /**
     * @return Last update time of the status.
     * 
     */
    public String updateTime() {
        return this.updateTime;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GoogleCloudDataplexV1AssetDiscoveryStatusResponse defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String lastRunDuration;
        private String lastRunTime;
        private String message;
        private String state;
        private GoogleCloudDataplexV1AssetDiscoveryStatusStatsResponse stats;
        private String updateTime;
        public Builder() {}
        public Builder(GoogleCloudDataplexV1AssetDiscoveryStatusResponse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.lastRunDuration = defaults.lastRunDuration;
    	      this.lastRunTime = defaults.lastRunTime;
    	      this.message = defaults.message;
    	      this.state = defaults.state;
    	      this.stats = defaults.stats;
    	      this.updateTime = defaults.updateTime;
        }

        @CustomType.Setter
        public Builder lastRunDuration(String lastRunDuration) {
            this.lastRunDuration = Objects.requireNonNull(lastRunDuration);
            return this;
        }
        @CustomType.Setter
        public Builder lastRunTime(String lastRunTime) {
            this.lastRunTime = Objects.requireNonNull(lastRunTime);
            return this;
        }
        @CustomType.Setter
        public Builder message(String message) {
            this.message = Objects.requireNonNull(message);
            return this;
        }
        @CustomType.Setter
        public Builder state(String state) {
            this.state = Objects.requireNonNull(state);
            return this;
        }
        @CustomType.Setter
        public Builder stats(GoogleCloudDataplexV1AssetDiscoveryStatusStatsResponse stats) {
            this.stats = Objects.requireNonNull(stats);
            return this;
        }
        @CustomType.Setter
        public Builder updateTime(String updateTime) {
            this.updateTime = Objects.requireNonNull(updateTime);
            return this;
        }
        public GoogleCloudDataplexV1AssetDiscoveryStatusResponse build() {
            final var o = new GoogleCloudDataplexV1AssetDiscoveryStatusResponse();
            o.lastRunDuration = lastRunDuration;
            o.lastRunTime = lastRunTime;
            o.message = message;
            o.state = state;
            o.stats = stats;
            o.updateTime = updateTime;
            return o;
        }
    }
}
