// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleCloud.Bigquery.V2.Inputs
{

    public sealed class StreamingbufferArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// [Output-only] A lower-bound estimate of the number of bytes currently in the streaming buffer.
        /// </summary>
        [Input("estimatedBytes")]
        public Input<string>? EstimatedBytes { get; set; }

        /// <summary>
        /// [Output-only] A lower-bound estimate of the number of rows currently in the streaming buffer.
        /// </summary>
        [Input("estimatedRows")]
        public Input<string>? EstimatedRows { get; set; }

        /// <summary>
        /// [Output-only] Contains the timestamp of the oldest entry in the streaming buffer, in milliseconds since the epoch, if the streaming buffer is available.
        /// </summary>
        [Input("oldestEntryTime")]
        public Input<string>? OldestEntryTime { get; set; }

        public StreamingbufferArgs()
        {
        }
    }
}
