// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.BigQuery.V2.Outputs
{

    [OutputType]
    public sealed class ExternalDataConfigurationResponse
    {
        /// <summary>
        /// Try to detect schema and format options automatically. Any option specified explicitly will be honored.
        /// </summary>
        public readonly bool Autodetect;
        /// <summary>
        /// [Optional] Additional options if sourceFormat is set to BIGTABLE.
        /// </summary>
        public readonly Outputs.BigtableOptionsResponse BigtableOptions;
        /// <summary>
        /// [Optional] The compression type of the data source. Possible values include GZIP and NONE. The default value is NONE. This setting is ignored for Google Cloud Bigtable, Google Cloud Datastore backups and Avro formats.
        /// </summary>
        public readonly string Compression;
        /// <summary>
        /// [Optional, Trusted Tester] Connection for external data source.
        /// </summary>
        public readonly string ConnectionId;
        /// <summary>
        /// Additional properties to set if sourceFormat is set to CSV.
        /// </summary>
        public readonly Outputs.CsvOptionsResponse CsvOptions;
        /// <summary>
        /// [Optional] Additional options if sourceFormat is set to GOOGLE_SHEETS.
        /// </summary>
        public readonly Outputs.GoogleSheetsOptionsResponse GoogleSheetsOptions;
        /// <summary>
        /// [Optional] Options to configure hive partitioning support.
        /// </summary>
        public readonly Outputs.HivePartitioningOptionsResponse HivePartitioningOptions;
        /// <summary>
        /// [Optional] Indicates if BigQuery should allow extra values that are not represented in the table schema. If true, the extra values are ignored. If false, records with extra columns are treated as bad records, and if there are too many bad records, an invalid error is returned in the job result. The default value is false. The sourceFormat property determines what BigQuery treats as an extra value: CSV: Trailing columns JSON: Named values that don't match any column names Google Cloud Bigtable: This setting is ignored. Google Cloud Datastore backups: This setting is ignored. Avro: This setting is ignored.
        /// </summary>
        public readonly bool IgnoreUnknownValues;
        /// <summary>
        /// [Optional] The maximum number of bad records that BigQuery can ignore when reading data. If the number of bad records exceeds this value, an invalid error is returned in the job result. This is only valid for CSV, JSON, and Google Sheets. The default value is 0, which requires that all records are valid. This setting is ignored for Google Cloud Bigtable, Google Cloud Datastore backups and Avro formats.
        /// </summary>
        public readonly int MaxBadRecords;
        /// <summary>
        /// Additional properties to set if sourceFormat is set to Parquet.
        /// </summary>
        public readonly Outputs.ParquetOptionsResponse ParquetOptions;
        /// <summary>
        /// [Optional] The schema for the data. Schema is required for CSV and JSON formats. Schema is disallowed for Google Cloud Bigtable, Cloud Datastore backups, and Avro formats.
        /// </summary>
        public readonly Outputs.TableSchemaResponse Schema;
        /// <summary>
        /// [Required] The data format. For CSV files, specify "CSV". For Google sheets, specify "GOOGLE_SHEETS". For newline-delimited JSON, specify "NEWLINE_DELIMITED_JSON". For Avro files, specify "AVRO". For Google Cloud Datastore backups, specify "DATASTORE_BACKUP". [Beta] For Google Cloud Bigtable, specify "BIGTABLE".
        /// </summary>
        public readonly string SourceFormat;
        /// <summary>
        /// [Required] The fully-qualified URIs that point to your data in Google Cloud. For Google Cloud Storage URIs: Each URI can contain one '*' wildcard character and it must come after the 'bucket' name. Size limits related to load jobs apply to external data sources. For Google Cloud Bigtable URIs: Exactly one URI can be specified and it has be a fully specified and valid HTTPS URL for a Google Cloud Bigtable table. For Google Cloud Datastore backups, exactly one URI can be specified. Also, the '*' wildcard character is not allowed.
        /// </summary>
        public readonly ImmutableArray<string> SourceUris;

        [OutputConstructor]
        private ExternalDataConfigurationResponse(
            bool autodetect,

            Outputs.BigtableOptionsResponse bigtableOptions,

            string compression,

            string connectionId,

            Outputs.CsvOptionsResponse csvOptions,

            Outputs.GoogleSheetsOptionsResponse googleSheetsOptions,

            Outputs.HivePartitioningOptionsResponse hivePartitioningOptions,

            bool ignoreUnknownValues,

            int maxBadRecords,

            Outputs.ParquetOptionsResponse parquetOptions,

            Outputs.TableSchemaResponse schema,

            string sourceFormat,

            ImmutableArray<string> sourceUris)
        {
            Autodetect = autodetect;
            BigtableOptions = bigtableOptions;
            Compression = compression;
            ConnectionId = connectionId;
            CsvOptions = csvOptions;
            GoogleSheetsOptions = googleSheetsOptions;
            HivePartitioningOptions = hivePartitioningOptions;
            IgnoreUnknownValues = ignoreUnknownValues;
            MaxBadRecords = maxBadRecords;
            ParquetOptions = parquetOptions;
            Schema = schema;
            SourceFormat = sourceFormat;
            SourceUris = sourceUris;
        }
    }
}
