// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

/**
 * Gets a SpecialistPool.
 */
export function getSpecialistPool(args: GetSpecialistPoolArgs, opts?: pulumi.InvokeOptions): Promise<GetSpecialistPoolResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("google-native:aiplatform/v1:getSpecialistPool", {
        "location": args.location,
        "project": args.project,
        "specialistPoolId": args.specialistPoolId,
    }, opts);
}

export interface GetSpecialistPoolArgs {
    location: string;
    project?: string;
    specialistPoolId: string;
}

export interface GetSpecialistPoolResult {
    /**
     * The user-defined name of the SpecialistPool. The name can be up to 128 characters long and can consist of any UTF-8 characters. This field should be unique on project-level.
     */
    readonly displayName: string;
    /**
     * The resource name of the SpecialistPool.
     */
    readonly name: string;
    /**
     * The resource name of the pending data labeling jobs.
     */
    readonly pendingDataLabelingJobs: string[];
    /**
     * The email addresses of the managers in the SpecialistPool.
     */
    readonly specialistManagerEmails: string[];
    /**
     * The number of managers in this SpecialistPool.
     */
    readonly specialistManagersCount: number;
    /**
     * The email addresses of workers in the SpecialistPool.
     */
    readonly specialistWorkerEmails: string[];
}
/**
 * Gets a SpecialistPool.
 */
export function getSpecialistPoolOutput(args: GetSpecialistPoolOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSpecialistPoolResult> {
    return pulumi.output(args).apply((a: any) => getSpecialistPool(a, opts))
}

export interface GetSpecialistPoolOutputArgs {
    location: pulumi.Input<string>;
    project?: pulumi.Input<string>;
    specialistPoolId: pulumi.Input<string>;
}
