// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleCloud.APIGateway.V1.Outputs
{

    [OutputType]
    public sealed class ApigatewayApiConfigFileResponse
    {
        /// <summary>
        /// The bytes that constitute the file.
        /// </summary>
        public readonly string Contents;
        /// <summary>
        /// The file path (full or relative path). This is typically the path of the file when it is uploaded.
        /// </summary>
        public readonly string Path;

        [OutputConstructor]
        private ApigatewayApiConfigFileResponse(
            string contents,

            string path)
        {
            Contents = contents;
            Path = path;
        }
    }
}
