// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.googlenative.dataproc.v1beta2.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAutoscalingPolicyIamPolicyArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAutoscalingPolicyIamPolicyArgs Empty = new GetAutoscalingPolicyIamPolicyArgs();

    @Import(name="autoscalingPolicyId", required=true)
    private Output<String> autoscalingPolicyId;

    public Output<String> autoscalingPolicyId() {
        return this.autoscalingPolicyId;
    }

    @Import(name="location", required=true)
    private Output<String> location;

    public Output<String> location() {
        return this.location;
    }

    @Import(name="optionsRequestedPolicyVersion")
    private @Nullable Output<String> optionsRequestedPolicyVersion;

    public Optional<Output<String>> optionsRequestedPolicyVersion() {
        return Optional.ofNullable(this.optionsRequestedPolicyVersion);
    }

    @Import(name="project")
    private @Nullable Output<String> project;

    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    private GetAutoscalingPolicyIamPolicyArgs() {}

    private GetAutoscalingPolicyIamPolicyArgs(GetAutoscalingPolicyIamPolicyArgs $) {
        this.autoscalingPolicyId = $.autoscalingPolicyId;
        this.location = $.location;
        this.optionsRequestedPolicyVersion = $.optionsRequestedPolicyVersion;
        this.project = $.project;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAutoscalingPolicyIamPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAutoscalingPolicyIamPolicyArgs $;

        public Builder() {
            $ = new GetAutoscalingPolicyIamPolicyArgs();
        }

        public Builder(GetAutoscalingPolicyIamPolicyArgs defaults) {
            $ = new GetAutoscalingPolicyIamPolicyArgs(Objects.requireNonNull(defaults));
        }

        public Builder autoscalingPolicyId(Output<String> autoscalingPolicyId) {
            $.autoscalingPolicyId = autoscalingPolicyId;
            return this;
        }

        public Builder autoscalingPolicyId(String autoscalingPolicyId) {
            return autoscalingPolicyId(Output.of(autoscalingPolicyId));
        }

        public Builder location(Output<String> location) {
            $.location = location;
            return this;
        }

        public Builder location(String location) {
            return location(Output.of(location));
        }

        public Builder optionsRequestedPolicyVersion(@Nullable Output<String> optionsRequestedPolicyVersion) {
            $.optionsRequestedPolicyVersion = optionsRequestedPolicyVersion;
            return this;
        }

        public Builder optionsRequestedPolicyVersion(String optionsRequestedPolicyVersion) {
            return optionsRequestedPolicyVersion(Output.of(optionsRequestedPolicyVersion));
        }

        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        public Builder project(String project) {
            return project(Output.of(project));
        }

        public GetAutoscalingPolicyIamPolicyArgs build() {
            $.autoscalingPolicyId = Objects.requireNonNull($.autoscalingPolicyId, "expected parameter 'autoscalingPolicyId' to be non-null");
            $.location = Objects.requireNonNull($.location, "expected parameter 'location' to be non-null");
            return $;
        }
    }

}
