// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleNative.CloudIdentity.V1.Outputs
{

    /// <summary>
    /// Contains information about browser profiles reported by the [Endpoint Verification extension](https://chromewebstore.google.com/detail/endpoint-verification/callobklhcbilhphinckomhgkigmfocg?pli=1).
    /// </summary>
    [OutputType]
    public sealed class GoogleAppsCloudidentityDevicesV1BrowserAttributesResponse
    {
        /// <summary>
        /// Represents the current state of the [Chrome browser attributes](https://cloud.google.com/access-context-manager/docs/browser-attributes) sent by the [Endpoint Verification extension](https://chromewebstore.google.com/detail/endpoint-verification/callobklhcbilhphinckomhgkigmfocg?pli=1).
        /// </summary>
        public readonly Outputs.GoogleAppsCloudidentityDevicesV1BrowserInfoResponse ChromeBrowserInfo;
        /// <summary>
        /// Chrome profile ID that is exposed by the Chrome API. It is unique for each device.
        /// </summary>
        public readonly string ChromeProfileId;
        /// <summary>
        /// Timestamp in milliseconds since Epoch when the profile/gcm id was last synced.
        /// </summary>
        public readonly string LastProfileSyncTime;

        [OutputConstructor]
        private GoogleAppsCloudidentityDevicesV1BrowserAttributesResponse(
            Outputs.GoogleAppsCloudidentityDevicesV1BrowserInfoResponse chromeBrowserInfo,

            string chromeProfileId,

            string lastProfileSyncTime)
        {
            ChromeBrowserInfo = chromeBrowserInfo;
            ChromeProfileId = chromeProfileId;
            LastProfileSyncTime = lastProfileSyncTime;
        }
    }
}
